# Generated by Django 4.2.28 on 2026-02-27 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import role_dietician.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_limit', models.FloatField(validators=[role_dietician.validators.validate_nutrition_limit], verbose_name='Ліміт білків (г)')),
                ('fat_limit', models.FloatField(validators=[role_dietician.validators.validate_nutrition_limit], verbose_name='Ліміт жирів (г)')),
                ('carbohydrate_limit', models.FloatField(validators=[role_dietician.validators.validate_nutrition_limit], verbose_name='Ліміт вуглеводів (г)')),
                ('kcal_limit', models.FloatField(validators=[role_dietician.validators.validate_nutrition_limit], verbose_name='Ліміт калорій (ккал)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DieticianFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(validators=[role_dietician.validators.validate_feedback_text], verbose_name='Текст поради')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('dietician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Дієтолог')),
            ],
        ),
    ]
