# Generated by Django 6.0.2 on 2026-02-25 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255, verbose_name='Назва страви/продукту')),
                ('calories', models.PositiveIntegerField(verbose_name='Калорії (ккал)')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Сніданок'), ('lunch', 'Обід'), ('dinner', 'Вечеря'), ('snack', 'Перекус')], max_length=20, verbose_name='Прийом їжі')),
                ('protein', models.FloatField(default=0, verbose_name='Білки (г)')),
                ('fat', models.FloatField(default=0, verbose_name='Жири (г)')),
                ('carbs', models.FloatField(default=0, verbose_name='Вуглеводи (г)')),
                ('fibre', models.FloatField(default=0, verbose_name='Клітковина (г)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час запису')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запис харчування',
                'verbose_name_plural': 'Записи харчування',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Чоловік'), ('F', 'Жінка')], max_length=1)),
                ('profile_type', models.CharField(choices=[('client', 'Клієнт'), ('dietician', 'Дієтолог')], default='client', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StressTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Рівень стресу')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Що сталося? (нотатки)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запису')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запис стресу',
                'verbose_name_plural': 'Записи стресу',
            },
        ),
    ]
