# Generated by Django 6.0.2 on 2026-02-25 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_database', '0002_sleeprecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DieticianClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата закріплення')),
                ('client', models.ForeignKey(limit_choices_to={'profile__profile_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='dieticians', to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
                ('dietician', models.ForeignKey(limit_choices_to={'profile__profile_type': 'dietician'}, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Дієтолог')),
            ],
            options={
                'verbose_name': "Зв'язок Дієтолог-Клієнт",
                'verbose_name_plural': "Зв'язки Дієтолог-Клієнт",
                'unique_together': {('dietician', 'client')},
            },
        ),
    ]
