# Generated by Django 6.0.2 on 2026-02-25 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_database', '0003_dieticianclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='calories',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Калорії (ккал)'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='carbs',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вуглеводи (г)'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='fat',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Жири (г)'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='fibre',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Клітковина (г)'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Білки (г)'),
        ),
    ]
