# Generated by Django 6.0.2 on 2026-02-28 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_database', '0004_alter_nutrition_calories_alter_nutrition_carbs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeprecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_sleep_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
