# Generated by Django 4.2.28 on 2026-02-26 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_database', '0004_alter_nutrition_calories_alter_nutrition_carbs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вік'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthdb_nutrition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sleeprecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthdb_sleep_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
