# Generated by Django 6.0.2 on 2026-02-20 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutrition',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='nutrition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='created_at',
        ),
    ]
