# Generated by Django 4.2.28 on 2026-02-27 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stress_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stressrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
