# Generated by Django 6.0.2 on 2026-02-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeprecord',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
