# Generated by Django 6.0.2 on 2026-02-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_tracker', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeprecord',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sleeprecord',
            name='end_time',
            field=models.DateTimeField(verbose_name='Прокинувся о'),
        ),
        migrations.AlterField(
            model_name='sleeprecord',
            name='start_time',
            field=models.DateTimeField(verbose_name='Заснув о'),
        ),
    ]
