# Generated by Django 6.0.2 on 2026-02-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_tracker', '0004_nutrition_stresstracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stresstracker',
            name='user',
        ),
        migrations.DeleteModel(
            name='Nutrition',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='StressTracker',
        ),
    ]
